version: "3"
services:
  bookstore-db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: bookstore
      POSTGRES_USER: bookstore
      POSTGRES_HOST_AUTH_METHOD: "trust"
  bookstore:
    build: .
    image: gcr.io/test-971a2/bookstore
    ports:
      - 3000:3000
    environment:
      DATABASE_HOST: bookstore-db
      DATABASE_USERNAME: bookstore
      DATABASE_PASSWORD: bookstore
    depends_on:
      - bookstore-db
volumes:
  db-data: ~
