name: CICD Staging BE
on:
  pull_request:
    types: [opened]
    branches:
      - master
  push:
    branches:
      - master
jobs:
  container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: test-971a2
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Install Google Cloud Docker
        run: gcloud components install docker-credential-gcr
      - name: Setup Docker for GCR
        run: gcloud auth configure-docker
      - name: Build Docker Image
        run: |
          echo ${{ secrets.RAILS_PRODUCTION_KEY }} > config/credentials/production.key
          docker build -t gcr.io/test-971a2/bookstore:${{github.event.number}} .
      - name: Push Docker Image
        run: docker push gcr.io/test-971a2/bookstore:${{github.event.number}}

  preview:
    runs-on: ubuntu-latest
    needs: [container]
    steps:
      - uses: actions/checkout@v3
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      - name: 'Deploy to App Engine'
        uses: 'google-github-actions/deploy-appengine@v0'
        with:
          deliverables: 'app-staging.yaml'
          promote: false
          version: 'v1'
