name: CICD Staging BE
on:
  pull_request:
    types: [opened]
    branches:
      - master
  push:
    branches:
      - master
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      DATABASE_HOST: localhost
      DATABASE_USERNAME: bookstore
      DATABASE_PASSWORD: bookstore
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: bookstore
          POSTGRES_USER: bookstore
        ports:
          - 5432:5432
  container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: test-971a2
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Install Google Cloud Docker
        run: gcloud components install docker-credential-gcr
      - name: Setup Docker for GCR
        run: gcloud auth configure-docker
      - name: Build Docker Image
        run: |
          echo ${{ secrets.RAILS_PRODUCTION_KEY }} > config/credentials/production.key
          docker build -t gcr.io/test-971a2/bookstore:${{github.event.number}} .
      - name: Push Docker Image
        run: docker push gcr.io/test-971a2/bookstore:${{github.event.number}}

  preview:
    runs-on: ubuntu-latest
    needs: [container]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: test-971a2
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Get HEAD Commit Hash
        id: commit
        run: echo "::set-output name=hash::$(git rev-parse --short HEAD)"
      - name: Deploy Revision On Cloud Run
        run: |
          gcloud run deploy bookstore-preview \
          --image=gcr.io/test-971a2/bookstore:${{github.event.number}} \
          --platform=managed \
          --port=3000 \
          --revision-suffix=${{github.event.number}}-${{steps.commit.outputs.hash}} \
          --add-cloudsql-instances=test-971a2:europe-north1:bookstore-db  \
          --set-env-vars DATABASE_HOST=/cloudsql/test-971a2:europe-north1:bookstore-db \
          --set-env-vars DATABASE_USERNAME='bookstore' \
          --set-env-vars DATABASE_PASSWORD='bookstore' \
          --set-env-vars DATABASE_NAME=bookstore_production_${{github.event.number}} \
          --set-env-vars RAILS_PRODUCTION_KEY=${{ secrets.RAILS_PRODUCTION_KEY }} \
          --allow-unauthenticated \
          --region=europe-north1
      - name: Update Traffic
        run: |
          gcloud components install beta
          gcloud beta run services update-traffic bookstore-preview \
            --update-tags pr-${{github.event.number}}=bookstore-preview-${{github.event.number}}-${{steps.commit.outputs.hash}} \
            --platform=managed \
            --region=europe-north1
